---
- name: Cleanup All Project01 Resources
  hosts: localhost
  connection: local
  vars_files:
    - ./global_vars/all_vars

  tasks:
    # 1. VPC ID 미리 조회 (VPC 삭제 시 필수)
    - name: Get VPC Info
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters: { "tag:Name": "{{ prefix }}-vpc" }
      register: vpc_info

    - name: Set VPC ID Fact
      set_fact:
        target_vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      when: vpc_info.vpcs | length > 0

    # 2. NAT Gateway 삭제 (안전한 필터 사용)
    - name: Get NAT Gateway Info
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ region }}"
        filters:
          state: ['available', 'pending']
      register: nat_info
      when: target_vpc_id is defined

    - name: Remove NAT Gateway
      amazon.aws.ec2_vpc_nat_gateway:
        nat_gateway_id: "{{ item.nat_gateway_id }}"
        state: absent
        region: "{{ region }}"
        wait: yes
      # nat_gateways 속성이 없을 경우를 대비해 default([])를 사용합니다.
      loop: "{{ nat_info.nat_gateways | default([]) }}"
      when: target_vpc_id is defined and (nat_info.nat_gateways | default([])) | length > 0
      ignore_errors: yes

    # 3. 서브넷 삭제 (AWS 조회 기반으로 변경하여 변수 오류 원천 차단)
    - name: Get Existing Subnets
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ target_vpc_id }}"
      register: current_subnets
      when: target_vpc_id is defined

    - name: Remove Subnets
      amazon.aws.ec2_vpc_subnet:
        region: "{{ region }}"
        vpc_id: "{{ target_vpc_id }}" # vpc_id는 필수 파라미터입니다.
        cidr: "{{ item.cidr_block }}"  # item.cidr_block으로 AWS에서 가져온 정보를 넘깁니다.
        state: absent
      loop: "{{ current_subnets.subnets | default([]) }}"
      when: target_vpc_id is defined and (current_subnets.subnets | length > 0)
      ignore_errors: yes

    # 4. VPC 최종 삭제 (ID 기반)
    - name: Remove VPC (Final Step)
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ target_vpc_id }}"
        region: "{{ region }}"
        state: absent
      when: target_vpc_id is defined
      ignore_errors: yes