---
- name: Cleanup All Project01 Resources
  hosts: localhost
  connection: local
  vars_files:
    - ./global_vars/all_vars

  tasks:
    # 0. VPC ID 조회 (삭제의 기준점이 됩니다)
    - name: Get VPC Info
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters: { "tag:Name": "{{ prefix }}-vpc" }
      register: vpc_info

    - name: Set VPC ID Fact
      set_fact:
        target_vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      when: vpc_info.vpcs | length > 0

    # 1. 고수준 자원 삭제 (이게 살아있으면 네트워크 삭제가 안 됩니다)
    - name: Remove Auto Scaling Group
      amazon.aws.autoscaling_group:
        name: "{{ prefix }}-was-asg"
        region: "{{ region }}"
        state: absent
        wait_for_instances: yes # 모든 인스턴스가 종료될 때까지 대기
      ignore_errors: yes

    - name: Remove Application Load Balancer
      amazon.aws.elb_application_lb:
        name: "{{ prefix }}-alb"
        region: "{{ region }}"
        state: absent
        wait: yes
      ignore_errors: yes

    - name: Remove Target Groups
      community.aws.elb_target_group:
        name: "{{ item }}"
        region: "{{ region }}"
        state: absent
      loop:
        - "{{ prefix }}-was-tg"
        - "{{ prefix }}-jenkins-tg"
      ignore_errors: yes

    # 2. 개별 인스턴스 종료
    - name: Terminate Jenkins Instance
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        filters: { "tag:Name": "{{ prefix }}-jenkins" }
        state: absent
        wait: yes
      ignore_errors: yes

    # 3. NAT 게이트웨이 및 EIP 삭제 (VPC 삭제를 막는 주범)
    - name: Get NAT Gateway Info
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ target_vpc_id }}"
          state: ['available', 'pending', 'deleting']
      register: nat_info
      when: target_vpc_id is defined

    - name: Remove NAT Gateway and WAIT
      amazon.aws.ec2_vpc_nat_gateway:
        region: "{{ region }}"
        nat_gateway_id: "{{ item.nat_gateway_id }}"
        state: absent
        wait: yes # 삭제가 완료될 때까지 기다려야 다음 단계 진행 가능
      loop: "{{ nat_info.nat_gateways | default([]) }}"
      when: target_vpc_id is defined and (nat_info.nat_gateways | length > 0)

    - name: Release NAT EIP
      amazon.aws.ec2_eip:
        region: "{{ region }}"
        tag_name: "Name"
        tag_value: "{{ prefix }}-nat-eip"
        state: absent
      ignore_errors: yes

    # 4. 인터넷 게이트웨이 분리 및 삭제 (필수 단계)
    - name: Remove Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ target_vpc_id }}"
        region: "{{ region }}"
        state: absent
      when: target_vpc_id is defined
      ignore_errors: yes

    # 5. 서브넷 및 VPC 최종 삭제
    - name: Get Remaining Subnets
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters: { "vpc-id": "{{ target_vpc_id }}" }
      register: current_subnets
      when: target_vpc_id is defined

    - name: Remove Subnets
      amazon.aws.ec2_vpc_subnet:
        region: "{{ region }}"
        vpc_id: "{{ target_vpc_id }}"
        cidr: "{{ item.cidr_block }}"
        state: absent
      loop: "{{ current_subnets.subnets | default([]) }}"
      when: target_vpc_id is defined and (current_subnets.subnets | length > 0)
      ignore_errors: yes

    - name: Remove VPC (Final Step)
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ target_vpc_id }}"
        region: "{{ region }}"
        state: absent
      when: target_vpc_id is defined