# deploy-network.yml 최종 수정본
- hosts: localhost
  connection: local
  vars_files:
    - ./global_vars/all_vars
  roles:
    - { role: network, tags: ["network"] }
    - { role: iam, tags: ["iam"] }
    - { role: security, tags: ["security"] }
    - { role: jenkins, tags: ["jenkins"] }
    #test    
    - { role: loadbalance, tags: ["loadbalance"] }
    - { role: asg, tags: ["asg"] }
    - { role: dns, tags: ["dns"] }
